ifndef::lang[:lang: pl]
ifndef::module[:module: .]

ifeval::["{lang}" == "pl"]
== Bezpieczeństwo

CAUTION: {device} jest urządzeniem amatorskim typu DIY.Instalacja i użytkowanie wymagają przestrzegania zasad bezpieczeństwa elektrycznego, urządzenie może być wykorzystywane wyłącznie do celów prywatnych.
Autor urządzenia nie ponosi odpowiedzialności za jego nieprawidłowe wykorzystywanie

WARNING: Urządzenie elektryczne po napięciem.
Przed dokonaniem jakichkolwiek czynności
związanych z zasilaniem (podłączanie przewodów,
instalacja urządzenia itd.) należy upewnić się, że
urządzenie jest odłączone od zasilania.
Montażu powinna dokonać osoba posiadająca
odpowiednie uprawnienia elektryczne

<<<
endif::[]

ifeval::["{lang}" == "en"]
== Safety

CAUTION: {device} is an amateur DIY device. Installation and use require adherence to electrical safety rules. The device may only be used for private purposes.  
The author of the device is not responsible for its improper use.

WARNING: Electrical device under voltage.  
Before performing any tasks related to power supply (connecting wires, installing the device, etc.), ensure that the device is disconnected from power.  
Installation should be carried out by a person with appropriate electrical qualifications.

<<<
endif::[]

